web:
  image: seqr-ecommerce-php-55
  ports:
    - "8080:80"
    - "3306:3306"
  expose:
    - "8080"
    - "3306"
  volumes_from:
    - data
data:
  image: seqr-prestashop-data
  environment:
    PS_VERSION: '1.6.1.3'
